# fly.toml app configuration file generated for realm-reborn on 2026-06-15T13:43:09-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'realm-reborn'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/app/data'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'realm_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
